#!/bin/bash
#
# Script to mount my configs on any Debian-based linux distro.
# Author: Jakku Night (@jakkunight on GitHub and XDA Developers, jakku_night on Twitch and Jakku Night on YouTube.)
#
# This script and configurations are based on my own preferences, so if you want to add or remove features, 
# feel free to fork/clone this repo (https://github.com/jakkunight/my-setup-settings) and do your stuffs.
# I'm not responsable for damaging your system, making your computer blow up or causing a thermonuclear war.
# YOU HAVE BEEN WARNED.


# Import modules:
source ./commons.sh
source ./shell.sh

# Print the welcome banner:
banner(){
	printf "${lblue}"
	printf "+------------------------------------------------------------------------------------------------------+\n"
	printf "|                                                                                                      |\n"
	printf "|                                      My Setup Settings (MSS)                                         |\n"
	printf "|                                    By @jakkunight (Jakku Night)                                      |\n"
	printf "|                                                                                                      |\n"
	printf "| This script and configurations are based on my own preferences, so if you want to add or remove      |\n"
	printf "| features, feel free to fork/clone this repo (https://github.com/jakkunight/my-setup-settings) and do |\n"
	printf "| your stuffs. I'm not responsable for damaging your system, making your computer blow up or causing   |\n"
	printf "| a thermonuclear war. YOU HAVE BEEN WARNED.                                                           |\n"
	printf "|                                                                                                      |\n"
	printf "+------------------------------------------------------------------------------------------------------+\n"
	printf "${reset}"
	return 0
}

basic(){
  if ! pkg curl wget zip unzip git aria2 alacritty sakura build-essential cmake clang; then
    abort "Cannot install the necessary tools to install/build the rest of the setup!"
  fi
  success "Tools installed!"
  return 0
}

# Execution:
banner
check_root
basic
shell_setup

