#!/bin/bash
#
# Script to mount my configs on any Debian-based linux distro.
# Author: Jakku Night (@jakkunight on GitHub and XDA Developers, jakku_night on Twitch and Jakku Night on YouTube.)
#
# This script and configurations are based on my own preferences, so if you want to add or remove features, 
# feel free to fork/clone this repo (https://github.com/jakkunight/my-setup-settings) and do your stuffs.
# I'm not responsable for damaging your system, making your computer blow up or causing a thermonuclear war.
# YOU HAVE BEEN WARNED.
#
# Terminal-based tools:

# Import common routines:
source ./common

# Tmux:
tmux_from_gh(){
	info "Installing tmux from GitHub..."
	if ! pkgman autoconf automake pkg-config; then
		warning "Couldn't install necessary tools to build tmux."
		info "Using pakage manager instead..."
		return 1
	fi
	if ! git clone https://github.com/tmux/tmux.git; then
		warning "Could not clone the repo."
		info "Using package manager instead..."
		return 1
	fi
	cd tmux
	if ! "$runas" ./autogen.sh; then
		warning "Couldn't generate the makefile."
		info ""
		info "Using pakage manager instead..."
		return 1
	fi
	if "$runas" ./configure && "$runas" make; then
		
	fi
}
terminal(){
	info "Installing terminal utilities..."
	
	if ! pkgman tmux; then
		warning "Could not install tmux!"
	fi
	success "Installed tmux!"
	info "Customizing tmux statusline..."
	info "Installing micro..."
	if ! pkgman micro; then
		warning "Could not install micro!"
	fi
	info "Customizing micro..."
	info "Installing htop, zsh, zsh-syntax-highlighting and zsh-autosuggestions..."
	if ! pkgman zsh zsh-syntax-highlighting zsh-autosuggestions htop;then
		error "Couldn't install zsh!"
	fi
	info "Customizing the terminal..."
	echo "source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" >> ${ZDOTDIR:-$HOME}/.zshrc
	info "Installing Powerlevel10k..."
	info "Using zsh as default shell..."
}
